[package]
name = "lego-star-wars-battles"
version = "0.1.1"
description = "Lego Star Wars Battles desktop app"
authors = ["Lego Star Wars Battles"]
edition = "2021"

[lib]
name = "lego_star_wars_battles_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
