import type { ScenarioDefinition } from "./scenario-types";

const deploymentZones: ScenarioDefinition["deploymentZones"] = [
  {
    id: "army-slot-0-entry",
    armySlot: 0,
    cells: Array.from({ length: 16 }, (_, index) => ({ x: Math.floor(index / 8), y: index % 8 })),
  },
  {
    id: "army-slot-1-entry",
    armySlot: 1,
    cells: Array.from({ length: 16 }, (_, index) => ({ x: 6 + Math.floor(index / 8), y: index % 8 })),
  },
];

function missionDirector(
  opening: "aggressive" | "defensive" | "hunter" | "objective" | "swarm",
  finale: "aggressive" | "defensive" | "hunter" | "objective" | "swarm",
  enemyWave: string,
  supportWave: string,
): ScenarioDefinition["missionDirector"] {
  return {
    playerArmySlot: 0,
    enemyArmySlot: 1,
    phaseProfiles: {
      Opening: opening,
      Escalation: "objective",
      Crisis: "hunter",
      Finale: finale,
    },
    escalation: {
      firstRound: 5,
      interval: 3,
      maxWaves: 2,
      powerRatioThreshold: 1.1,
      waves: [
        [{ templateId: enemyWave, count: 1 }],
        [{ templateId: "super_battle_droid_squad", count: 1 }],
      ],
    },
    emergencySupport: {
      firstRound: 6,
      strengthBelowPercentage: 35,
      maxUses: 1,
      cooldownRounds: 3,
      waves: [[{ templateId: supportWave, count: 1 }]],
    },
  };
}

export const tatooineGhostRelayScenario: ScenarioDefinition = {
  id: "tatooine-ghost-relay",
  name: "Tatooine: Widmowy przekaźnik",
  description: "Odszukaj dwa zakopane przekaźniki Separatystów i prześlij ich dane, zanim pustynny garnizon odetnie drogę odwrotu.",
  experience: "NarrativeMission",
  planet: "Tatooine",
  recommendedMapThemeId: "desert-outpost",
  recommendedPoints: 105,
  mapPreset: { themeId: "desert-outpost", seed: 160816, width: 8, height: 8, terrainDensity: 0.34 },
  defaultDefenderArmySlot: 1,
  missionDirector: missionDirector("defensive", "hunter", "stap_patrol", "clone_commando_section"),
  deploymentZones,
  objectives: [{
    id: "decode-ghost-relays",
    name: "Odszukaj widmowe przekaźniki",
    description: "Zajmij kolejno oba ukryte terminale na szlaku przez pustynię.",
    victoryPoints: 1,
  }],
  scheduledEvents: [{
    id: "tatooine-relay-awakens",
    name: "Przekaźnik budzi pustynny garnizon",
    trigger: { type: "RoundStarted", round: 5 },
    effect: { type: "ChangeAIProfile", armyId: "army_separatists", profile: "hunter" },
    visibility: "Announced",
  }, {
    id: "tatooine-stap-screen",
    name: "Patrol STAP przecina szlak",
    trigger: { type: "RoundStarted", round: 7 },
    effect: { type: "DeployReinforcements", armyId: "army_separatists", units: [{ templateId: "stap_patrol", count: 1 }] },
    visibility: "Announced",
  }],
  victoryCondition: {
    type: "ProgressiveControl",
    objectiveType: "StrategicPoint",
    count: 2,
    attackerArmySlot: 0,
    roundLimit: 12,
    stageRoundLimits: [6, 6],
  },
  defeatCondition: { type: "ArmyEliminated", armySlot: 0 },
};

export const endorBrokenCanopyScenario: ScenarioDefinition = {
  id: "endor-broken-canopy",
  name: "Endor: Pęknięta korona",
  description: "Po zasadzce w koronach drzew utrzymaj zwiadowców przy życiu, a następnie przebij się do lądowiska po przeciwnej stronie puszczy.",
  experience: "NarrativeMission",
  planet: "Endor",
  recommendedMapThemeId: "forest-moon",
  recommendedPoints: 100,
  mapPreset: { themeId: "forest-moon", seed: 51804, width: 8, height: 8, terrainDensity: 0.47 },
  defaultDefenderArmySlot: 0,
  missionDirector: missionDirector("swarm", "hunter", "b1_recon_squad", "clone_medic_squad"),
  deploymentZones,
  zones: [{
    id: "endor-evacuation",
    type: "Extraction",
    cells: Array.from({ length: 6 }, (_, y) => ({ x: 7, y: y + 1 })),
  }],
  objectives: [{
    id: "escape-broken-canopy",
    name: "Wyrwij się z okrążenia",
    description: "Przetrwaj pięć rund, po czym wyprowadź co najmniej dwie jednostki na lądowisko.",
    victoryPoints: 1,
  }],
  scheduledEvents: [{
    id: "endor-recon-ambush",
    name: "Zwiadowcy B1 schodzą z platform",
    trigger: { type: "RoundStarted", round: 3 },
    effect: { type: "DeployReinforcements", armyId: "army_separatists", units: [{ templateId: "b1_recon_squad", count: 1 }] },
    visibility: "Announced",
  }, {
    id: "endor-path-opens",
    name: "Rex odnajduje szlak ewakuacyjny",
    trigger: { type: "RoundStarted", round: 5 },
    effect: { type: "ShowMessage", message: "Droga przez korony drzew jest otwarta. Kieruj oddział ku wschodniemu lądowisku." },
    visibility: "Announced",
  }],
  victoryCondition: {
    type: "SurviveAndExtract",
    armySlot: 0,
    minimumRounds: 5,
    roundLimit: 11,
    minimumUnits: 2,
    zoneId: "endor-evacuation",
  },
  defeatCondition: { type: "ArmyEliminated", armySlot: 0 },
};

export const hothWhiteSilenceScenario: ScenarioDefinition = {
  id: "hoth-white-silence",
  name: "Hoth: Biała cisza",
  description: "Chroń prototypowy nadajnik dalekiego zasięgu, dopóki burza jonowa nie przekaże jego sygnału flocie.",
  experience: "NarrativeMission",
  planet: "Hoth",
  recommendedMapThemeId: "ice-front",
  recommendedPoints: 100,
  mapPreset: { themeId: "ice-front", seed: 40481, width: 8, height: 8, terrainDensity: 0.31 },
  defaultDefenderArmySlot: 0,
  missionDirector: missionDirector("objective", "aggressive", "dwarf_spider_droid", "clone_medic_squad"),
  deploymentZones,
  objectDurability: { Generator: { maxHp: 14, armorSave: 4 } },
  objectives: [{
    id: "protect-hoth-transmitter",
    name: "Chroń nadajnik",
    description: "Utrzymaj generator sygnału przez siedem pełnych rund.",
    victoryPoints: 1,
  }],
  scheduledEvents: [{
    id: "hoth-whiteout",
    name: "Nadciąga całkowita zamieć",
    trigger: { type: "RoundStarted", round: 4 },
    effect: { type: "ChangeAIProfile", armyId: "army_separatists", profile: "objective" },
    visibility: "Announced",
  }, {
    id: "hoth-relief",
    name: "Sygnał przebija burzę",
    trigger: { type: "RoundStarted", round: 6 },
    effect: { type: "DeployReinforcements", armyId: "army_republic", units: [{ templateId: "at_rt_scout_walker", count: 1 }] },
    visibility: "Announced",
  }],
  victoryCondition: { type: "ProtectObject", rounds: 7, objectType: "Generator" },
  defeatCondition: { type: "BattlefieldObjectDestroyed", objectType: "Generator" },
};

export const mustafarBlackFurnaceScenario: ScenarioDefinition = {
  id: "mustafar-black-furnace",
  name: "Mustafar: Czarny piec",
  description: "Zejdź do głównej odlewni i zniszcz trzy węzły chłodzenia, zanim fabryka rozpocznie produkcję nowej armii.",
  experience: "NarrativeMission",
  planet: "Mustafar",
  recommendedMapThemeId: "volcanic-foundry",
  recommendedPoints: 120,
  mapPreset: { themeId: "volcanic-foundry", seed: 1, width: 8, height: 8, terrainDensity: 0.4 },
  defaultDefenderArmySlot: 1,
  missionDirector: missionDirector("defensive", "aggressive", "super_battle_droid_squad", "clone_engineers_332nd"),
  deploymentZones,
  objectDurability: { Generator: { maxHp: 9, armorSave: 5 } },
  objectives: [{
    id: "break-black-furnace",
    name: "Wygaszaj piec sektor po sektorze",
    description: "Zniszcz trzy rozdzielone węzły chłodzenia przed końcem czternastej rundy.",
    victoryPoints: 1,
  }],
  scheduledEvents: [{
    id: "mustafar-foundry-awakens",
    name: "Linia produkcyjna przyspiesza",
    trigger: { type: "RoundStarted", round: 5 },
    effect: { type: "DeployReinforcements", armyId: "army_separatists", units: [{ templateId: "b1_droid_regiment", count: 1 }] },
    visibility: "Announced",
  }, {
    id: "mustafar-meltdown",
    name: "Odlewnia wchodzi w stan krytyczny",
    trigger: { type: "RoundStarted", round: 10 },
    effect: { type: "ChangeAIProfile", armyId: "army_separatists", profile: "aggressive" },
    visibility: "Announced",
  }],
  victoryCondition: { type: "DestroyObjects", objectType: "Generator", count: 3, roundLimit: 14 },
  defeatCondition: { type: "ArmyEliminated", armySlot: 0 },
};

export const geonosisLastTemplateScenario: ScenarioDefinition = {
  id: "geonosis-last-template",
  name: "Geonosis: Ostatnia matryca",
  description: "Zdobądź matrycę taktyczną z zamkniętego archiwum fabryki i dostarcz ją do punktu ewakuacji.",
  experience: "NarrativeMission",
  planet: "Geonosis",
  recommendedMapThemeId: "geonosis-foundry",
  recommendedPoints: 120,
  mapPreset: { themeId: "geonosis-foundry", seed: 77142, width: 8, height: 8, terrainDensity: 0.43 },
  defaultDefenderArmySlot: 1,
  missionDirector: missionDirector("defensive", "hunter", "magnaguard_squad", "clone_commando_section"),
  deploymentZones,
  objectives: [{
    id: "extract-last-template",
    name: "Przejmij ostatnią matrycę",
    description: "Zabezpiecz archiwum, a następnie dotrzyj z danymi do punktu ewakuacji.",
    victoryPoints: 1,
  }],
  objectivePresentation: [
    { name: "Archiwum matrycy", visualId: "hostage" },
    { name: "Punkt ewakuacji", visualId: "extraction" },
  ],
  scheduledEvents: [{
    id: "geonosis-template-lockdown",
    name: "Archiwum uruchamia blokadę",
    trigger: { type: "RoundStarted", round: 5 },
    effect: { type: "ChangeAIProfile", armyId: "army_separatists", profile: "hunter" },
    visibility: "Announced",
  }, {
    id: "geonosis-template-guard",
    name: "Magnagwardzi ruszają do archiwum",
    trigger: { type: "RoundStarted", round: 8 },
    effect: { type: "DeployReinforcements", armyId: "army_separatists", units: [{ templateId: "magnaguard_squad", count: 1 }] },
    visibility: "Announced",
  }],
  victoryCondition: {
    type: "RescueAndExtract",
    objectiveType: "StrategicPoint",
    hostageCount: 1,
    rescuerArmySlot: 0,
    roundLimit: 14,
    stageRoundLimits: [7, 7],
  },
  defeatCondition: { type: "ArmyEliminated", armySlot: 0 },
};

export const feluciaLostPatrolScenario: ScenarioDefinition = {
  id: "felucia-lost-patrol",
  name: "Felucia: Zaginiony patrol",
  description: "Odnajdź dwa odcięte zespoły badawcze i wyprowadź je przez grzybowe ostępy do kanonierki.",
  experience: "NarrativeMission",
  planet: "Felucia",
  recommendedMapThemeId: "felucia-wilds",
  recommendedPoints: 110,
  mapPreset: { themeId: "felucia-wilds", seed: 5, width: 8, height: 8, terrainDensity: 0.5 },
  defaultDefenderArmySlot: 1,
  missionDirector: missionDirector("swarm", "hunter", "b1_recon_squad", "clone_medic_squad"),
  deploymentZones,
  objectives: [{
    id: "rescue-felucia-patrol",
    name: "Odnajdź zaginionych",
    description: "Przejmij kolejno oba znaczniki patroli i zabezpiecz lądowisko.",
    victoryPoints: 1,
  }],
  objectivePresentation: [
    { name: "Patrol Aurek", visualId: "hostage" },
    { name: "Patrol Besh", visualId: "hostage" },
    { name: "Lądowisko kanonierki", visualId: "extraction" },
  ],
  scheduledEvents: [{
    id: "felucia-spores-stir",
    name: "Ruch wśród zarodników",
    trigger: { type: "RoundStarted", round: 4 },
    effect: { type: "DeployReinforcements", armyId: "army_separatists", units: [{ templateId: "b1_recon_squad", count: 1 }] },
    visibility: "Announced",
  }, {
    id: "felucia-gunship-signal",
    name: "Kanonierka odbiera sygnał",
    trigger: { type: "RoundStarted", round: 10 },
    effect: { type: "DeployReinforcements", armyId: "army_republic", units: [{ templateId: "laat_patrol", count: 1 }] },
    visibility: "Announced",
  }],
  victoryCondition: {
    type: "RescueAndExtract",
    objectiveType: "StrategicPoint",
    hostageCount: 2,
    rescuerArmySlot: 0,
    roundLimit: 16,
    stageRoundLimits: [5, 5, 6],
  },
  defeatCondition: { type: "ArmyEliminated", armySlot: 0 },
};

export const christophsisZeroJunctionScenario: ScenarioDefinition = {
  id: "christophsis-zero-junction",
  name: "Christophsis: Węzeł zero",
  description: "Rozegraj bitwę o trzy dzielnice skupione wokół głównego węzła energetycznego Kryształowego Miasta.",
  experience: "NarrativeMission",
  planet: "Christophsis",
  recommendedMapThemeId: "christophsis-crystal-city",
  recommendedPoints: 130,
  mapPreset: { themeId: "christophsis-crystal-city", seed: 33018, width: 8, height: 8, terrainDensity: 0.38 },
  defaultDefenderArmySlot: 1,
  missionDirector: missionDirector("objective", "aggressive", "b1_droid_regiment", "clone_assault_squad"),
  deploymentZones,
  objectives: [{
    id: "control-zero-junction",
    name: "Przejmij węzeł zero",
    description: "Zdobywaj sektory i utrzymuj przewagę punktową przez dziesięć rund.",
    victoryPoints: 1,
  }],
  scheduledEvents: [{
    id: "zero-junction-center",
    name: "Węzeł centralny wchodzi do sieci",
    trigger: { type: "RoundStarted", round: 4 },
    effect: { type: "ShowMessage", message: "Centralny sektor jest aktywny. Punkty strategiczne zdecydują o wyniku bitwy." },
    visibility: "Announced",
  }, {
    id: "zero-junction-counterattack",
    name: "Kontratak z kryształowej alei",
    trigger: { type: "RoundStarted", round: 7 },
    effect: { type: "DeployReinforcements", armyId: "army_separatists", units: [{ templateId: "super_battle_droid_squad", count: 1 }] },
    visibility: "Announced",
  }],
  victoryCondition: { type: "ControlTerritory", rounds: 10, winnerArmySlot: 0 },
};

export const mandalorePalaceUnderSiegeScenario: ScenarioDefinition = {
  id: "mandalore-palace-under-siege",
  name: "Mandalore: Pałac pod oblężeniem",
  description: "Utrzymaj główny plac pałacowy, gdy Maul i łowcy próbują przełamać ostatni pierścień obrony Sundari.",
  experience: "NarrativeMission",
  planet: "Mandalore",
  recommendedMapThemeId: "mandalore-city",
  recommendedPoints: 120,
  mapPreset: { themeId: "mandalore-city", seed: 62016, width: 8, height: 8, terrainDensity: 0.4 },
  defaultDefenderArmySlot: 0,
  missionDirector: missionDirector("aggressive", "hunter", "bx_commando_droid", "clone_command_squad"),
  deploymentZones,
  objectives: [{
    id: "hold-sundari-palace",
    name: "Utrzymaj pałac",
    description: "Kontroluj plac pałacowy przez sześć pełnych rund przed końcem dwunastej rundy.",
    victoryPoints: 1,
  }],
  scheduledEvents: [{
    id: "mandalore-maul-arrives",
    name: "Maul prowadzi szturm",
    trigger: { type: "RoundStarted", round: 4 },
    effect: { type: "ChangeAIProfile", armyId: "army_separatists", profile: "hunter" },
    visibility: "Announced",
  }, {
    id: "mandalore-palace-guard",
    name: "Straż pałacowa wzmacnia barykady",
    trigger: { type: "RoundStarted", round: 6 },
    effect: { type: "DeployReinforcements", armyId: "army_republic", units: [{ templateId: "clone_command_squad", count: 1 }] },
    visibility: "Announced",
  }],
  victoryCondition: {
    type: "DefendPoint",
    rounds: 6,
    roundLimit: 12,
    defenderArmySlot: 0,
    objectiveType: "DefensePoint",
  },
  defeatCondition: { type: "ArmyEliminated", armySlot: 0 },
};

export const rylothStormOverLessuScenario: ScenarioDefinition = {
  id: "ryloth-storm-over-lessu",
  name: "Ryloth: Burza nad Lessu",
  description: "Przełam pierścień artylerii otaczający Lessu i zniszcz dwa generatory naprowadzania przed rozpoczęciem bombardowania.",
  experience: "NarrativeMission",
  planet: "Ryloth",
  recommendedMapThemeId: "ryloth-badlands",
  recommendedPoints: 115,
  mapPreset: { themeId: "ryloth-badlands", seed: 80821, width: 8, height: 8, terrainDensity: 0.4 },
  defaultDefenderArmySlot: 1,
  missionDirector: missionDirector("defensive", "objective", "stap_patrol", "clone_commando_section"),
  deploymentZones,
  objectDurability: { Generator: { maxHp: 11, armorSave: 4 } },
  objectives: [{
    id: "silence-lessu-artillery",
    name: "Ucisz artylerię",
    description: "Zniszcz dwa generatory naprowadzania w głębi kanionów.",
    victoryPoints: 1,
  }],
  scheduledEvents: [{
    id: "ryloth-artillery-lock",
    name: "Artyleria namierza Lessu",
    trigger: { type: "RoundStarted", round: 6 },
    effect: { type: "ChangeAIProfile", armyId: "army_separatists", profile: "objective" },
    visibility: "Announced",
  }, {
    id: "ryloth-canyon-riders",
    name: "STAP-y wychodzą z bocznego kanionu",
    trigger: { type: "RoundStarted", round: 8 },
    effect: { type: "DeployReinforcements", armyId: "army_separatists", units: [{ templateId: "stap_patrol", count: 1 }] },
    visibility: "Announced",
  }],
  victoryCondition: { type: "DestroyObjects", objectType: "Generator", count: 2, roundLimit: 13 },
  defeatCondition: { type: "ArmyEliminated", armySlot: 0 },
};

export const researchStationProjectEchoScenario: ScenarioDefinition = {
  id: "research-station-project-echo",
  name: "Stacja badawcza: Projekt Echo",
  description: "Odzyskaj trzy fragmenty projektu Echo z laboratoriów opanowanych przez grupę abordażową Separatystów.",
  experience: "NarrativeMission",
  planet: "Republic Research Station",
  recommendedMapThemeId: "republic-research-station",
  recommendedPoints: 120,
  mapPreset: { themeId: "republic-research-station", seed: 2, width: 8, height: 8, terrainDensity: 0.44 },
  defaultDefenderArmySlot: 1,
  missionDirector: missionDirector("defensive", "hunter", "bx_commando_droid", "clone_medic_squad"),
  deploymentZones,
  objectives: [{
    id: "recover-project-echo",
    name: "Odzyskaj Projekt Echo",
    description: "Zabezpiecz kolejno trzy terminale laboratoryjne, zanim dane zostaną wymazane.",
    victoryPoints: 1,
  }],
  scheduledEvents: [{
    id: "echo-data-purge",
    name: "Rozpoczyna się czyszczenie danych",
    trigger: { type: "RoundStarted", round: 5 },
    effect: { type: "ShowMessage", message: "Separatyści rozpoczęli kasowanie Projektu Echo. Kolejne terminale mają ograniczone okno dostępu." },
    visibility: "Announced",
  }, {
    id: "echo-commando-hunt",
    name: "Droidy komandosów przeczesują laboratoria",
    trigger: { type: "RoundStarted", round: 8 },
    effect: { type: "DeployReinforcements", armyId: "army_separatists", units: [{ templateId: "bx_commando_droid", count: 1 }] },
    visibility: "Announced",
  }],
  victoryCondition: {
    type: "ProgressiveControl",
    objectiveType: "StrategicPoint",
    count: 3,
    attackerArmySlot: 0,
    roundLimit: 15,
    stageRoundLimits: [5, 5, 5],
  },
  defeatCondition: { type: "ArmyEliminated", armySlot: 0 },
};

export const separatistWarshipBridgefallScenario: ScenarioDefinition = {
  id: "separatist-warship-bridgefall",
  name: "Okręt Separatystów: Upadek mostka",
  description: "Przebij się przez pokłady dowodzenia i zniszcz dwa węzły zasilania mostka, zanim Grievous odetnie sekcję szturmową.",
  experience: "NarrativeMission",
  planet: "Separatist Warship",
  recommendedMapThemeId: "separatist-warship",
  recommendedPoints: 135,
  mapPreset: { themeId: "separatist-warship", seed: 77201, width: 8, height: 8, terrainDensity: 0.44 },
  defaultDefenderArmySlot: 1,
  missionDirector: missionDirector("defensive", "hunter", "magnaguard_squad", "clone_command_squad"),
  deploymentZones,
  objectDurability: { Generator: { maxHp: 12, armorSave: 4 } },
  objectives: [{
    id: "disable-separatist-bridge",
    name: "Odłącz mostek",
    description: "Zniszcz oba węzły zasilania rozmieszczone w głębi okrętu.",
    victoryPoints: 1,
  }],
  scheduledEvents: [{
    id: "bridgefall-lockdown",
    name: "Grievous zamyka grodzie",
    trigger: { type: "RoundStarted", round: 5 },
    effect: { type: "ChangeAIProfile", armyId: "army_separatists", profile: "hunter" },
    visibility: "Announced",
  }, {
    id: "bridgefall-magnaguards",
    name: "Magnagwardzi ruszają do węzłów",
    trigger: { type: "RoundStarted", round: 8 },
    effect: { type: "DeployReinforcements", armyId: "army_separatists", units: [{ templateId: "magnaguard_squad", count: 1 }] },
    visibility: "Announced",
  }],
  victoryCondition: { type: "DestroyObjects", objectType: "Generator", count: 2, roundLimit: 14 },
  defeatCondition: { type: "ArmyEliminated", armySlot: 0 },
};

export const republicWarshipDeckSeventeenScenario: ScenarioDefinition = {
  id: "republic-warship-deck-seventeen",
  name: "Okręt Republiki: Pokład siedemnasty",
  description: "Odeprzyj abordaż na pokładzie siedemnastym i utrzymaj reaktor hipernapędu do chwili odcięcia wrogich kapsuł.",
  experience: "NarrativeMission",
  planet: "Republic Warship",
  recommendedMapThemeId: "republic-warship",
  recommendedPoints: 135,
  mapPreset: { themeId: "republic-warship", seed: 17017, width: 8, height: 8, terrainDensity: 0.4 },
  defaultDefenderArmySlot: 0,
  missionDirector: missionDirector("aggressive", "objective", "bx_commando_droid", "clone_medic_squad"),
  deploymentZones,
  objectDurability: { Generator: { maxHp: 15, armorSave: 4 } },
  objectives: [{
    id: "hold-deck-seventeen",
    name: "Chroń reaktor hipernapędu",
    description: "Nie dopuść do zniszczenia reaktora przez osiem pełnych rund.",
    victoryPoints: 1,
  }],
  scheduledEvents: [{
    id: "deck-seventeen-breach",
    name: "Kapsuła abordażowa przebija poszycie",
    trigger: { type: "RoundStarted", round: 3 },
    effect: { type: "DeployReinforcements", armyId: "army_separatists", units: [{ templateId: "bx_commando_droid", count: 1 }] },
    visibility: "Announced",
  }, {
    id: "deck-seventeen-medics",
    name: "Zespół medyczny dociera do reaktora",
    trigger: { type: "RoundStarted", round: 5 },
    effect: { type: "DeployReinforcements", armyId: "army_republic", units: [{ templateId: "clone_medic_squad", count: 1 }] },
    visibility: "Announced",
  }, {
    id: "deck-seventeen-final-assault",
    name: "Ostatnie uderzenie abordażowe",
    trigger: { type: "RoundStarted", round: 7 },
    effect: { type: "ChangeAIProfile", armyId: "army_separatists", profile: "aggressive" },
    visibility: "Announced",
  }],
  victoryCondition: { type: "ProtectObject", rounds: 8, objectType: "Generator" },
  defeatCondition: { type: "BattlefieldObjectDestroyed", objectType: "Generator" },
};

export const campaignPrologueMissions: ScenarioDefinition[] = [
  tatooineGhostRelayScenario,
  endorBrokenCanopyScenario,
  hothWhiteSilenceScenario,
  mustafarBlackFurnaceScenario,
  geonosisLastTemplateScenario,
  feluciaLostPatrolScenario,
  christophsisZeroJunctionScenario,
  mandalorePalaceUnderSiegeScenario,
  rylothStormOverLessuScenario,
  researchStationProjectEchoScenario,
  separatistWarshipBridgefallScenario,
  republicWarshipDeckSeventeenScenario,
];
