import type { AbilityDefinition, Army, Board, TaskForceDefinition, UnitTemplate } from "./types";

export const unitTemplates: UnitTemplate[] = [
  {
    id: "clone_trooper_battalion",
    name: "Clone Trooper Battalion",
    faction: "Republic",
    category: "infantry",
    imageUrl: "/unit-images/photos/clone-trooper.jpg",
    role: "Line",
    keywords: ["Clone", "Infantry"],
    weapons: [
      {
        id: "dc_15_blaster_rifles",
        name: "DC-15 Blaster Rifles",
        range: 2,
        attacks: 3,
        damage: 1,
        keywords: ["RapidFire"],
      },
    ],
    maxHp: 3,
    armorSave: 6,
    movement: 1,
    morale: 5,
    command: 3,
    abilities: ["clone_training"],
    cost: 20,
  },
  {
    id: "jedi_task_force",
    name: "Jedi Task Force",
    faction: "Republic",
    category: "hero",
    imageUrl: "/unit-images/jedi-task-force-scifi.png",
    role: "Commander",
    keywords: ["Jedi", "ForceUser", "Infantry"],
    weapons: [
      {
        id: "lightsabers",
        name: "Lightsabers",
        range: 1,
        attacks: 4,
        damage: 2,
        keywords: ["Pierce", "Deflect"],
      },
    ],
    maxHp: 5,
    armorSave: 5,
    movement: 2,
    morale: 8,
    command: 8,
    abilities: [
      "master_tactician",
      "force_prediction",
      "defensive_mastery",
      "inspiration",
    ],
    cost: 60,
  },
  {
    id: "laat_patrol",
    name: "LAAT Patrol",
    faction: "Republic",
    category: "vehicle",
    imageUrl: "/unit-images/laat-patrol.png",
    role: "Heavy",
    keywords: ["Vehicle", "Repulsor", "Transport"],
    weapons: [
      {
        id: "laat_laser_cannons",
        name: "Laser Cannons",
        range: 3,
        attacks: 3,
        damage: 2,
        keywords: ["Blast"],
      },
    ],
    maxHp: 6,
    armorSave: 4,
    movement: 2,
    morale: 6,
    command: 2,
    abilities: ["air_support"],
    cost: 55,
  },
  {
    id: "b1_droid_regiment",
    name: "B1 Droid Regiment",
    faction: "Separatists",
    category: "droid",
    imageUrl: "/unit-images/photos/b1-battle-droid.jpg",
    role: "Line",
    keywords: ["Droid", "Infantry"],
    weapons: [
      {
        id: "e_5_blaster_rifles",
        name: "E-5 Blaster Rifles",
        range: 2,
        attacks: 3,
        damage: 1,
        keywords: [],
      },
    ],
    maxHp: 3,
    armorSave: 6,
    movement: 1,
    morale: 3,
    command: 2,
    abilities: ["mass_production"],
    cost: 15,
  },
  {
    id: "droideka_cell",
    name: "Droideka Cell",
    faction: "Separatists",
    category: "droid",
    imageUrl: "/unit-images/photos/droideka.jpg",
    role: "Support",
    keywords: ["Droid", "Infantry", "Shielded"],
    weapons: [
      {
        id: "twin_blaster_cannons",
        name: "Twin Blaster Cannons",
        range: 2,
        attacks: 2,
        damage: 1,
        keywords: ["Shielded"],
      },
    ],
    maxHp: 4,
    armorSave: 4,
    movement: 2,
    morale: 5,
    command: 1,
    abilities: ["shield_generators"],
    cost: 35,
  },
  {
    id: "super_battle_droid_squad",
    name: "B2 Super Battle Droid Squad",
    faction: "Separatists",
    category: "droid",
    imageUrl: "/unit-images/photos/b2-super-battle-droid.jpg",
    role: "Heavy",
    keywords: ["Droid", "Infantry", "Armor", "SuperBattleDroid"],
    weapons: [
      {
        id: "wrist_blaster_array",
        name: "Wrist Blaster Array",
        range: 2,
        attacks: 3,
        damage: 2,
        keywords: ["Pierce"],
      },
    ],
    maxHp: 5,
    armorSave: 5,
    movement: 1,
    morale: 5,
    command: 1,
    abilities: ["reinforced_chassis"],
    cost: 40,
  },
  {
    id: "aat_battle_tank",
    name: "AAT Battle Tank",
    faction: "Separatists",
    category: "vehicle",
    imageUrl: "/unit-images/aat-battle-tank.png",
    role: "Heavy",
    keywords: ["Vehicle", "Armor"],
    weapons: [
      {
        id: "aat_heavy_cannon",
        name: "Heavy Cannon",
        range: 3,
        attacks: 2,
        damage: 3,
        keywords: ["AntiVehicle", "Blast"],
      },
    ],
    maxHp: 7,
    armorSave: 4,
    movement: 1,
    morale: 6,
    command: 2,
    abilities: ["heavy_cannon"],
    cost: 65,
  },
  {
    id: "yoda",
    name: "Yoda",
    faction: "Republic",
    category: "hero",
    imageUrl: "/unit-images/photos/yoda.jpg",
    role: "support/control",
    keywords: ["Hero", "Jedi", "ForceUser", "Commander"],
    weapons: [
      {
        id: "yoda_lightsaber",
        name: "Lightsaber",
        range: 1,
        attacks: 6,
        damage: 1,
        keywords: ["Pierce", "Deflect"],
      },
    ],
    maxHp: 18,
    armorSave: 3,
    movement: 2,
    morale: 9,
    command: 9,
    abilities: ["master_of_the_order", "force_push"],
    cost: 32,
  },
  {
    id: "obi_wan_kenobi",
    name: "Obi-Wan Kenobi",
    faction: "Republic",
    category: "hero",
    imageUrl: "/unit-images/photos/obi-wan-kenobi.jpg",
    role: "tank/defense",
    keywords: ["Hero", "Jedi", "ForceUser", "Commander"],
    weapons: [
      {
        id: "obi_wan_lightsaber",
        name: "Lightsaber",
        range: 1,
        attacks: 5,
        damage: 1,
        keywords: ["Pierce", "Deflect"],
      },
    ],
    maxHp: 24,
    armorSave: 2,
    movement: 2,
    morale: 9,
    command: 8,
    abilities: ["soresu_master", "defensive_stance"],
    cost: 34,
  },
  {
    id: "anakin_skywalker",
    name: "Anakin Skywalker",
    faction: "Republic",
    category: "hero",
    imageUrl: "/unit-images/photos/anakin-skywalker.jpg",
    role: "assault/damage",
    keywords: ["Hero", "Jedi", "ForceUser", "Commander"],
    weapons: [
      {
        id: "anakin_lightsaber",
        name: "Lightsaber",
        range: 1,
        attacks: 8,
        damage: 1,
        keywords: ["Pierce", "Deflect"],
      },
    ],
    maxHp: 20,
    armorSave: 4,
    movement: 2,
    morale: 9,
    command: 7,
    abilities: ["the_chosen_one", "heroic_charge"],
    cost: 35,
  },
  {
    id: "clone_trooper_squad",
    name: "Clone Trooper Squad",
    faction: "Republic",
    category: "infantry",
    role: "basic infantry",
    imageUrl: "/unit-images/photos/clone-trooper.jpg",
    keywords: ["Clone", "Infantry"],
    weapons: [
      {
        id: "clone_squad_blaster_rifles",
        name: "DC-15 Blaster Rifles",
        range: 2,
        attacks: 4,
        damage: 1,
        keywords: [],
      },
    ],
    maxHp: 10,
    armorSave: 5,
    movement: 1,
    morale: 5,
    command: 3,
    abilities: [],
    cost: 10,
  },
  {
    id: "clone_command_squad",
    name: "Clone Command Squad",
    faction: "Republic",
    category: "commander",
    role: "command/support",
    imageUrl: "/unit-images/photos/clone-command-squad.jpg",
    keywords: ["Clone", "Infantry", "Commander"],
    weapons: [
      {
        id: "command_squad_blaster_rifles",
        name: "DC-15 Blaster Rifles",
        range: 2,
        attacks: 4,
        damage: 1,
        keywords: [],
      },
    ],
    maxHp: 11,
    armorSave: 5,
    movement: 1,
    morale: 6,
    command: 5,
    abilities: ["battlefield_coordination"],
    cost: 14,
  },
  {
    id: "clone_assault_squad",
    name: "Clone Assault Squad",
    faction: "Republic",
    category: "infantry",
    role: "assault",
    imageUrl: "/unit-images/photos/clone-assault-squad.jpg",
    keywords: ["Clone", "Infantry"],
    weapons: [
      {
        id: "assault_blaster_carbines",
        name: "Blaster Carbines",
        range: 1,
        attacks: 5,
        damage: 1,
        keywords: ["RapidFire"],
      },
    ],
    maxHp: 11,
    armorSave: 5,
    movement: 2,
    morale: 5,
    command: 3,
    abilities: ["assault_training"],
    cost: 14,
  },
  {
    id: "clone_engineers_332nd",
    name: "Clone Engineers / 332nd Support Squad",
    faction: "Republic",
    category: "infantry",
    role: "engineering/support",
    imageUrl: "/unit-images/photos/clone-engineers.jpg",
    keywords: ["Clone", "Infantry", "Engineer", "332nd"],
    weapons: [
      {
        id: "engineer_blaster_rifles",
        name: "DC-15 Blaster Rifles",
        range: 2,
        attacks: 3,
        damage: 1,
        keywords: [],
      },
    ],
    maxHp: 10,
    armorSave: 5,
    movement: 1,
    morale: 5,
    command: 4,
    abilities: ["build_cover", "repair"],
    cost: 13,
  },
  {
    id: "b1_droid_squad",
    name: "B1 Droid Squad",
    faction: "Separatists",
    category: "droid",
    role: "basic infantry",
    imageUrl: "/unit-images/photos/b1-battle-droid.jpg",
    keywords: ["Droid", "Infantry"],
    weapons: [
      {
        id: "b1_squad_e_5_blaster_rifles",
        name: "E-5 Blaster Rifles",
        range: 2,
        attacks: 3,
        damage: 1,
        keywords: [],
      },
    ],
    maxHp: 8,
    armorSave: 6,
    movement: 1,
    morale: 3,
    command: 1,
    abilities: ["mass_production"],
    cost: 8,
  },
  {
    id: "asajj_ventress",
    name: "Asajj Ventress",
    faction: "Separatists",
    category: "hero",
    imageUrl: "/unit-images/photos/asajj-ventress.jpg",
    role: "assassin",
    keywords: ["Hero", "Sith", "ForceUser", "Infantry"],
    weapons: [
      {
        id: "ventress_lightsabers",
        name: "Twin Lightsabers",
        range: 1,
        attacks: 7,
        damage: 1,
        keywords: ["Pierce"],
      },
    ],
    maxHp: 18,
    armorSave: 4,
    movement: 2,
    morale: 8,
    command: 5,
    abilities: ["assassin", "shadow_strike"],
    cost: 32,
  },
  {
    id: "jango_fett",
    name: "Jango Fett",
    faction: "Separatists",
    category: "hero",
    imageUrl: "/unit-images/photos/jango-fett.jpg",
    role: "bounty hunter/skirmisher",
    keywords: ["Hero", "BountyHunter", "Mandalorian", "Infantry", "Jetpack"],
    weapons: [
      {
        id: "jango_dual_westars",
        name: "Dual WESTAR-34 Blasters",
        range: 2,
        attacks: 6,
        damage: 1,
        keywords: ["RapidFire"],
      },
    ],
    maxHp: 16,
    armorSave: 4,
    movement: 2,
    morale: 8,
    command: 4,
    abilities: ["bounty_hunter", "jetpack_reposition", "wrist_rockets"],
    cost: 31,
  },
  {
    id: "darth_maul",
    name: "Darth Maul",
    faction: "Separatists",
    category: "hero",
    imageUrl: "/unit-images/photos/darth-maul.jpg",
    role: "assault/duelist",
    keywords: ["Hero", "Sith", "ForceUser", "Infantry"],
    weapons: [
      {
        id: "maul_saberstaff",
        name: "Double-Bladed Lightsaber",
        range: 1,
        attacks: 8,
        damage: 1,
        keywords: ["Pierce"],
      },
    ],
    maxHp: 20,
    armorSave: 4,
    movement: 2,
    morale: 9,
    command: 5,
    abilities: ["relentless_fury", "saberstaff_duelist", "saber_throw"],
    cost: 34,
  },
  {
    id: "ahsoka_tano",
    name: "Ahsoka Tano",
    faction: "Republic",
    category: "hero",
    imageUrl: "/unit-images/photos/ahsoka-tano.jpg",
    role: "mobile duelist/support",
    keywords: ["Hero", "Jedi", "ForceUser", "Infantry"],
    weapons: [
      {
        id: "ahsoka_twin_lightsabers",
        name: "Twin Lightsabers",
        range: 1,
        attacks: 6,
        damage: 1,
        keywords: ["Pierce", "Deflect"],
      },
    ],
    maxHp: 18,
    armorSave: 3,
    movement: 2,
    morale: 8,
    command: 6,
    abilities: ["ataru_momentum", "jar_kai_mastery", "force_prediction"],
    cost: 34,
  },
  {
    id: "arc_trooper",
    name: "ARC Trooper",
    faction: "Republic",
    category: "infantry",
    imageUrl: "/unit-images/photos/arc-trooper.jpg",
    role: "elite assault",
    keywords: ["Clone", "Infantry", "Elite"],
    weapons: [
      {
        id: "arc_blaster_carbine",
        name: "ARC Blaster Carbine",
        range: 2,
        attacks: 5,
        damage: 1,
        keywords: ["RapidFire"],
      },
    ],
    maxHp: 12,
    armorSave: 4,
    movement: 2,
    morale: 7,
    command: 4,
    abilities: ["assault_training", "battlefield_coordination"],
    cost: 20,
  },
  {
    id: "commander_cody",
    name: "Commander Cody",
    faction: "Republic",
    category: "commander",
    imageUrl: "/unit-images/photos/commander-cody.jpg",
    role: "command/ranged support",
    keywords: ["Hero", "Clone", "Infantry", "Commander"],
    weapons: [
      {
        id: "cody_dc_15a_rifle",
        name: "DC-15A Blaster Rifle",
        range: 3,
        attacks: 5,
        damage: 1,
        keywords: [],
      },
    ],
    maxHp: 16,
    armorSave: 3,
    movement: 1,
    morale: 8,
    command: 8,
    abilities: ["battlefield_coordination", "calm_leadership"],
    cost: 27,
  },
  {
    id: "captain_rex",
    name: "Captain Rex",
    faction: "Republic",
    category: "commander",
    imageUrl: "/unit-images/photos/captain-rex.jpg",
    role: "mobile commander",
    keywords: ["Hero", "Clone", "Infantry", "Commander"],
    weapons: [
      {
        id: "rex_dual_dc_17",
        name: "Dual DC-17 Blasters",
        range: 2,
        attacks: 6,
        damage: 1,
        keywords: ["RapidFire"],
      },
    ],
    maxHp: 17,
    armorSave: 3,
    movement: 2,
    morale: 8,
    command: 8,
    abilities: ["battlefield_coordination", "aggressive_advance"],
    cost: 29,
  },
  {
    id: "bx_commando_droid",
    name: "BX Commando Droid",
    faction: "Separatists",
    category: "droid",
    imageUrl: "/unit-images/photos/bx-commando-droid.jpg",
    role: "elite infiltrator",
    keywords: ["Droid", "Infantry", "Elite"],
    weapons: [
      {
        id: "bx_blaster_rifle",
        name: "E-5 Blaster Rifle",
        range: 2,
        attacks: 4,
        damage: 1,
        keywords: [],
      },
      {
        id: "bx_vibrosword",
        name: "Vibrosword",
        range: 1,
        attacks: 4,
        damage: 1,
        keywords: ["Pierce"],
      },
    ],
    maxHp: 10,
    armorSave: 5,
    movement: 2,
    morale: 5,
    command: 2,
    abilities: ["assassin", "shadow_strike"],
    cost: 19,
  },
  {
    id: "stap_patrol",
    name: "STAP Patrol",
    faction: "Separatists",
    category: "vehicle",
    imageUrl: "/unit-images/photos/stap-patrol.jpg",
    role: "fast reconnaissance",
    keywords: ["Droid", "Vehicle", "Repulsor"],
    weapons: [
      {
        id: "stap_twin_blaster_cannons",
        name: "Twin Blaster Cannons",
        range: 2,
        attacks: 3,
        damage: 1,
        keywords: ["RapidFire"],
      },
    ],
    maxHp: 8,
    armorSave: 5,
    movement: 2,
    morale: 4,
    command: 1,
    abilities: [],
    cost: 18,
  },
  {
    id: "at_rt_scout_walker",
    name: "AT-RT Scout Walker",
    faction: "Republic",
    category: "vehicle",
    imageUrl: "/unit-images/photos/at-rt-scout-walker.jpg",
    role: "fast fire support",
    keywords: ["Clone", "Vehicle", "Walker"],
    weapons: [
      {
        id: "at_rt_rotary_blaster",
        name: "Rotary Blaster Cannon",
        range: 3,
        attacks: 4,
        damage: 2,
        keywords: ["AntiVehicle"],
      },
    ],
    maxHp: 11,
    armorSave: 4,
    movement: 2,
    morale: 6,
    command: 2,
    abilities: [],
    cost: 26,
  },
];

export const abilities: AbilityDefinition[] = [
  {
    id: "clone_training",
    name: "Clone Training",
    type: "passive",
    trigger: "OnAttack",
    effect: { type: "hit_bonus_without_suppression", value: 1 },
    description: "+1 do rzutu ataku, gdy jednostka nie ma suppression.",
  },
  {
    id: "master_tactician",
    name: "Master Tactician",
    type: "passive",
    trigger: "OnActivation",
    effect: { type: "flexible_commander_activation" },
    description: "Po dobraniu tokena armii dowodca moze w przyszlosci rozszerzac wybor aktywacji.",
  },
  {
    id: "ataru_momentum",
    name: "Ataru Momentum",
    type: "passive",
    trigger: "OnAttack",
    effect: { type: "attack_bonus_if_moved", value: 1 },
    description: "Jeśli Ahsoka poruszyła się przed atakiem w tej turze, otrzymuje +1 atak.",
  },
  {
    id: "jar_kai_mastery",
    name: "Jar'Kai Mastery",
    type: "passive",
    trigger: "OnAttack",
    effect: { type: "attack_bonus_against_category", value: 1, target: "hero" },
    description: "Ahsoka otrzymuje +1 atak podczas atakowania jednostek hero.",
  },
  {
    id: "force_prediction",
    name: "Force Prediction",
    type: "passive",
    trigger: "OnDefense",
    effect: { type: "damage_reduction", value: 1 },
    description: "Pierwsze obrażenie z każdego ataku przeciw tej jednostce jest ignorowane.",
  },
  {
    id: "defensive_mastery",
    name: "Defensive Mastery",
    type: "passive",
    trigger: "Passive",
    effect: { type: "morale_bonus", value: 1 },
    description: "+1 morale podczas testów przypięcia.",
  },
  {
    id: "inspiration",
    name: "Inspiration",
    type: "aura",
    range: 1,
    trigger: "EndTurn",
    effect: { type: "remove_suppression", value: 1 },
    description: "Jedna sojusznicza jednostka w zasięgu usuwa 1 suppression.",
  },
  {
    id: "mass_production",
    name: "Mass Production",
    type: "passive",
    trigger: "Passive",
    effect: { type: "army_build_discount" },
    description: "Ta jednostka jest tania i może występować licznie w armii.",
  },
  {
    id: "shield_generators",
    name: "Shield Generators",
    type: "passive",
    trigger: "OnDefense",
    effect: { type: "ranged_shield_damage_reduction", value: 3 },
    description: "Przeciw atakom dystansowym redukuje do 3 obrażeń z każdego ataku.",
  },
  {
    id: "heavy_cannon",
    name: "Heavy Cannon",
    type: "passive",
    trigger: "OnAttack",
    effect: { type: "anti_vehicle_damage_bonus", value: 1 },
    description: "+1 obrażenie przeciw pojazdom.",
  },
  {
    id: "reinforced_chassis",
    name: "Reinforced Chassis",
    type: "passive",
    trigger: "OnDefense",
    effect: { type: "damage_reduction", value: 1 },
    description: "Pierwsze obrażenie z każdego ataku przeciw tej jednostce jest ignorowane.",
  },
  {
    id: "air_support",
    name: "Air Support",
    type: "passive",
    trigger: "OnActivation",
    effect: { type: "ignore_difficult_terrain" },
    description: "Może ignorować trudny teren podczas rozkazu Advance.",
  },
  {
    id: "master_of_the_order",
    name: "Master of the Order",
    type: "aura",
    trigger: "Passive",
    range: 1,
    effect: { type: "aura_attack_bonus", value: 1, target: "friendly_clone" },
    description: "Sojusznicze jednostki klonow w zasiegu 2 otrzymuja +1 atak.",
  },
  {
    id: "force_push",
    name: "Force Push",
    type: "active",
    trigger: "OnActivation",
    range: 2,
    cooldown: 3,
    effect: { type: "damage_and_push", value: 4, target: "enemy" },
    description: "Zadaje 4 obrazenia i wypycha cel o 1 pole, jesli to mozliwe.",
  },
  {
    id: "soresu_master",
    name: "Soresu Master",
    type: "passive",
    trigger: "OnDefense",
    effect: { type: "first_incoming_damage_reduction_per_turn", value: 2 },
    description: "Raz na ture redukuje pierwsze otrzymane obrazenia o 2.",
  },
  {
    id: "defensive_stance",
    name: "Defensive Stance",
    type: "active",
    trigger: "OnActivation",
    cooldown: 3,
    effect: { type: "incoming_damage_multiplier", value: 50, target: "self" },
    description: "Do nastepnej aktywacji Obi-Wan otrzymuje o 50% mniej obrazen.",
  },
  {
    id: "the_chosen_one",
    name: "The Chosen One",
    type: "passive",
    trigger: "OnAttack",
    effect: { type: "move_after_destroying_unit", value: 1 },
    description: "Po zniszczeniu wrogiej jednostki Anakin moze poruszyc sie o 1 dodatkowe pole.",
  },
  {
    id: "heroic_charge",
    name: "Heroic Charge",
    type: "active",
    trigger: "OnActivation",
    cooldown: 3,
    effect: { type: "bonus_move_then_melee_attack", value: 2, target: "self" },
    description: "Anakin porusza sie do 2 dodatkowych pol i natychmiast wykonuje atak w zwarciu.",
  },
  {
    id: "battlefield_coordination",
    name: "Battlefield Coordination",
    type: "aura",
    trigger: "Passive",
    range: 1,
    effect: { type: "aura_attack_bonus", value: 1, target: "friendly_clone" },
    description: "Sojusznicze jednostki klonow w zasiegu 1 otrzymuja +1 atak.",
  },
  {
    id: "assault_training",
    name: "Assault Training",
    type: "passive",
    trigger: "OnAttack",
    effect: { type: "attack_bonus_if_moved", value: 1 },
    description: "Jesli jednostka ruszyla sie przed atakiem w tej turze, otrzymuje +1 atak.",
  },
  {
    id: "build_cover",
    name: "Build Cover",
    type: "active",
    trigger: "OnActivation",
    range: 1,
    cooldown: 3,
    effect: { type: "create_light_cover", target: "adjacent_empty_tile" },
    description: "Tworzy lekka oslone na sasiednim pustym polu.",
  },
  {
    id: "repair",
    name: "Repair",
    type: "active",
    trigger: "OnActivation",
    range: 1,
    cooldown: 2,
    effect: { type: "restore_hp", value: 3, target: "friendly_vehicle" },
    description: "Przygotowane pod pojazdy: przywraca 3 HP sojuszniczemu pojazdowi.",
  },
  {
    id: "assassin",
    name: "Assassin",
    type: "passive",
    trigger: "OnAttack",
    effect: { type: "damage_bonus_against_category", value: 2, target: "hero" },
    description: "Ventress zadaje +2 obrazenia przeciw jednostkom hero.",
  },
  {
    id: "shadow_strike",
    name: "Shadow Strike",
    type: "active",
    trigger: "OnAttack",
    cooldown: 3,
    effect: { type: "move_after_attack", value: 1, target: "self" },
    description: "Po ataku Ventress moze odsunac sie o 1 pole od celu, jesli to mozliwe.",
  },
  {
    id: "bounty_hunter",
    name: "Bounty Hunter",
    type: "passive",
    trigger: "OnAttack",
    effect: { type: "damage_bonus_against_category", value: 2, target: "hero" },
    description: "Jango zadaje +2 obrazenia przeciw jednostkom hero.",
  },
  {
    id: "jetpack_reposition",
    name: "Jetpack Reposition",
    type: "active",
    trigger: "OnActivation",
    cooldown: 2,
    effect: { type: "bonus_move_ignore_terrain", value: 2, target: "self" },
    description: "Jango moze przemieścić się do 2 pol, ignorując koszt terenu. Przygotowane pod UI aktywnych zdolnosci.",
  },
  {
    id: "wrist_rockets",
    name: "Wrist Rockets",
    type: "active",
    trigger: "OnAttack",
    cooldown: 3,
    range: 2,
    effect: { type: "direct_damage", value: 3, target: "enemy_in_cover" },
    description: "Atak specjalny przeciw celom w oslonie: 3 obrazenia w zasiegu 3. Przygotowane pod UI aktywnych zdolnosci.",
  },
  {
    id: "relentless_fury",
    name: "Relentless Fury",
    type: "passive",
    trigger: "OnAttack",
    effect: { type: "attack_bonus_when_damaged", value: 1 },
    description: "Gdy Maul jest ranny, otrzymuje +1 atak.",
  },
  {
    id: "saberstaff_duelist",
    name: "Saberstaff Duelist",
    type: "passive",
    trigger: "OnAttack",
    effect: { type: "attack_bonus_against_category", value: 1, target: "hero" },
    description: "Maul otrzymuje +1 atak podczas atakowania jednostek hero.",
  },
  {
    id: "saber_throw",
    name: "Saber Throw",
    type: "active",
    trigger: "OnAttack",
    range: 2,
    cooldown: 3,
    effect: { type: "direct_damage", value: 4, target: "enemy" },
    description: "Maul moze rzucic mieczem: 4 obrazenia w zasiegu 2. Przygotowane pod UI aktywnych zdolnosci.",
  },
  {
    id: "calm_leadership",
    name: "Calm Leadership",
    type: "aura",
    trigger: "Passive",
    range: 1,
    effect: { type: "task_force_defense_bonus_near_unit", value: 1, target: "friendly_clone" },
    description: "Klonowe jednostki z task force'a otrzymuja +1 defense w zasiegu 2 od Yody.",
  },
  {
    id: "hold_the_line",
    name: "Hold the Line",
    type: "passive",
    trigger: "OnDefense",
    effect: { type: "task_force_cover_defense_bonus", value: 1 },
    description: "Jednostki z task force'a otrzymuja +1 defense w oslonie lub na celu.",
  },
  {
    id: "aggressive_advance",
    name: "Aggressive Advance",
    type: "active",
    trigger: "OnActivation",
    cooldown: 1,
    effect: { type: "task_force_once_per_turn_movement_bonus", value: 1, target: "friendly_clone" },
    description: "Raz na ture jedna klonowa jednostka z task force'a moze otrzymac +1 ruch.",
  },
  {
    id: "ruthless_strike",
    name: "Ruthless Strike",
    type: "active",
    trigger: "OnAttack",
    cooldown: 1,
    effect: { type: "task_force_attack_bonus_against_damaged", value: 1, target: "friendly_droid" },
    description: "Raz na ture jeden droid z task force'a otrzymuje +1 atak przeciw uszkodzonemu celowi.",
  },
  {
    id: "marked_target",
    name: "Marked Target",
    type: "active",
    trigger: "OnAttack",
    cooldown: 1,
    effect: { type: "task_force_attack_bonus_against_hero", value: 1, target: "friendly_droid" },
    description: "Raz na ture jeden droid z task force'a Jango otrzymuje +1 atak przeciw bohaterowi.",
  },
  {
    id: "fear_and_momentum",
    name: "Fear and Momentum",
    type: "aura",
    trigger: "Passive",
    range: 1,
    effect: { type: "task_force_aura_attack_bonus", value: 1, target: "friendly_droid" },
    description: "Droidy z task force'a Maula w zasiegu 1 otrzymuja +1 atak.",
  },
];

export const taskForces: TaskForceDefinition[] = [
  {
    id: "yoda_task_force",
    name: "Yoda Task Force",
    faction: "Republic",
    heroId: "yoda",
    unitIds: ["yoda", "clone_command_squad", "clone_trooper_squad"],
    cost: 53,
    bonusAbility: "calm_leadership",
  },
  {
    id: "obi_wan_task_force",
    name: "Obi-Wan Task Force",
    faction: "Republic",
    heroId: "obi_wan_kenobi",
    unitIds: ["obi_wan_kenobi", "clone_engineers_332nd", "clone_trooper_squad"],
    cost: 54,
    bonusAbility: "hold_the_line",
  },
  {
    id: "anakin_task_force",
    name: "Anakin Task Force",
    faction: "Republic",
    heroId: "anakin_skywalker",
    unitIds: ["anakin_skywalker", "clone_assault_squad", "clone_trooper_squad"],
    cost: 56,
    bonusAbility: "aggressive_advance",
  },
  {
    id: "ventress_task_force",
    name: "Ventress Task Force",
    faction: "Separatists",
    heroId: "asajj_ventress",
    unitIds: ["asajj_ventress", "b1_droid_squad", "super_battle_droid_squad"],
    cost: 77,
    bonusAbility: "ruthless_strike",
  },
  {
    id: "jango_task_force",
    name: "Jango Fett Task Force",
    faction: "Separatists",
    heroId: "jango_fett",
    unitIds: ["jango_fett", "b1_droid_squad", "super_battle_droid_squad"],
    cost: 76,
    bonusAbility: "marked_target",
  },
  {
    id: "maul_task_force",
    name: "Darth Maul Task Force",
    faction: "Separatists",
    heroId: "darth_maul",
    unitIds: ["darth_maul", "b1_droid_squad", "droideka_cell"],
    cost: 74,
    bonusAbility: "fear_and_momentum",
  },
];

export const board: Board = {
  width: 8,
  height: 8,
  tiles: [
    {
      x: 3,
      y: 2,
      terrainType: "LightCover",
      defenseBonus: 1,
      attackBonus: 0,
      movementCost: 1,
      blocksLineOfSight: false,
    },
    {
      x: 4,
      y: 3,
      terrainType: "HeavyCover",
      defenseBonus: 2,
      attackBonus: 0,
      movementCost: 2,
      blocksLineOfSight: false,
    },
    {
      x: 5,
      y: 1,
      terrainType: "DifficultTerrain",
      defenseBonus: 0,
      attackBonus: 0,
      movementCost: 2,
      blocksLineOfSight: false,
    },
  ],
};

export const starterArmies: Army[] = [
  {
    id: "army_republic",
    playerName: "Gracz Republiki",
    faction: "Republic",
    units: [
      {
        id: "rep_unit_1",
        templateId: "clone_trooper_battalion",
        armyId: "army_republic",
        currentHp: 3,
        suppression: 0,
        position: { x: 1, y: 2 },
        status: "Ready",
        hidden: false,
      },
      {
        id: "rep_unit_2",
        templateId: "jedi_task_force",
        armyId: "army_republic",
        currentHp: 5,
        suppression: 0,
        position: { x: 1, y: 3 },
        status: "Ready",
        hidden: false,
      },
      {
        id: "rep_unit_3",
        templateId: "laat_patrol",
        armyId: "army_republic",
        currentHp: 6,
        suppression: 0,
        position: { x: 0, y: 2 },
        status: "Ready",
        hidden: false,
      },
    ],
  },
  {
    id: "army_separatists",
    playerName: "Gracz Separatystow",
    faction: "Separatists",
    units: [
      {
        id: "sep_unit_1",
        templateId: "b1_droid_regiment",
        armyId: "army_separatists",
        currentHp: 3,
        suppression: 0,
        position: { x: 6, y: 2 },
        status: "Ready",
        hidden: false,
      },
      {
        id: "sep_unit_2",
        templateId: "droideka_cell",
        armyId: "army_separatists",
        currentHp: 4,
        suppression: 0,
        position: { x: 6, y: 3 },
        status: "Ready",
        hidden: false,
      },
      {
        id: "sep_unit_3",
        templateId: "aat_battle_tank",
        armyId: "army_separatists",
        currentHp: 7,
        suppression: 0,
        position: { x: 7, y: 2 },
        status: "Ready",
        hidden: false,
      },
    ],
  },
];
